In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set

In [4]:
import os
os.getcwd()

'C:\\Users\\SRUTHI\\OneDrive\\Desktop\\Weekly task'

In [5]:
import os
os.getcwd()
import pandas as pd

df = pd.read_csv(r"C:\\Users\\SRUTHI\\OneDrive\\Desktop\\Weekly task\samplesuperstore.csv")
print("Dataset loaded successfully")

Dataset loaded successfully

In [6]:
 # shows full dataframe or dataset records with all column
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,12/30/2026,1/3/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,12/30/2026,1/3/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [7]:
# Frist 5 rows
df.head

<bound method NDFrame.head of        Row ID        Order ID  Order Date  Ship Date       Ship Mode  \
0           1  US-2023-103800    1/3/2023   1/7/2023  Standard Class
1           2  US-2023-112326    1/4/2023   1/8/2023  Standard Class
2           3  US-2023-112326    1/4/2023   1/8/2023  Standard Class
3           4  US-2023-112326    1/4/2023   1/8/2023  Standard Class
4           5  US-2023-141817    1/5/2023  1/12/2023  Standard Class
...       ...             ...         ...        ...             ...
10189   10190  US-2026-143259  12/30/2026   1/3/2027  Standard Class
10190   10191  US-2026-115427  12/30/2026   1/3/2027  Standard Class
10191   10192  US-2026-156720  12/30/2026   1/3/2027  Standard Class
10192   10193  US-2026-143259  12/30/2026   1/3/2027  Standard Class
10193   10194  CA-2026-143500  12/30/2026   1/3/2027  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ... Postal Code   Region       Product ID  \
0            Houston  ...       77095  Central  OFF-PA-10000174
1         Naperville  ...       60540  Central  OFF-BI-10004094
2         Naperville  ...       60540  Central  OFF-LA-10003223
3         Naperville  ...       60540  Central  OFF-ST-10002743
4       Philadelphia  ...       19143     East  OFF-AR-10003478
...              ...  ...         ...      ...              ...
10189  New York City  ...       10009     East  OFF-BI-10003684
10190      Fairfield  ...       94533     West  OFF-BI-10004632
10191       Loveland  ...       80538     West  OFF-FA-10003472
10192  New York City  ...       10009     East  TEC-PH-10004774
10193  Charlottetown  ...         C0A     East  OFF-BI-10004040

              Category Sub-Category  \
0      Office Supplies        Paper
1      Office Supplies      Binders
2      Office Supplies       Labels
3      Office Supplies      Storage
4      Office Supplies          Art
...                ...          ...
10189  Office Supplies      Binders
10190  Office Supplies      Binders
10191  Office Supplies    Fasteners
10192       Technology       Phones
10193  Office Supplies      Binders

                                            Product Name    Sales  Quantity  \
0      Message Book, Wirebound, Four 5 1/2" X 4" Form...   16.448         2
1             GBC Standard Plastic Binding Systems Combs    3.540         2
2                                              Avery 508   11.784         3
3                          SAFCO Boltless Steel Shelving  272.736         3
4      Avery Hi-Liter EverBold Pen Style Fluorescent ...   19.536         3
...                                                  ...      ...       ...
10189               Wilson Jones Legal Size Ring Binders   52.776         3
10190                                 GBC Binding covers   20.720         2
10191                                Bagged Rubber Bands    3.024         3
10192                          Gear Head AU3700S Headset   90.930         7
10193                        Wilson Jones Impact Binders    3.024         3

       Discount   Profit
0           0.2   5.5512
1           0.8  -5.4870
2           0.2   4.2717
3           0.2 -64.7748
4           0.2   4.8840
...         ...      ...
10189       0.2  19.7910
10190       0.2   6.4750
10191       0.2  -0.6048
10192       0.0   2.7279
10193       0.2  -0.6048

[10194 rows x 21 columns]>

In [8]:
# Last five rows
df.tail

<bound method NDFrame.tail of        Row ID        Order ID  Order Date  Ship Date       Ship Mode  \
0           1  US-2023-103800    1/3/2023   1/7/2023  Standard Class
1           2  US-2023-112326    1/4/2023   1/8/2023  Standard Class
2           3  US-2023-112326    1/4/2023   1/8/2023  Standard Class
3           4  US-2023-112326    1/4/2023   1/8/2023  Standard Class
4           5  US-2023-141817    1/5/2023  1/12/2023  Standard Class
...       ...             ...         ...        ...             ...
10189   10190  US-2026-143259  12/30/2026   1/3/2027  Standard Class
10190   10191  US-2026-115427  12/30/2026   1/3/2027  Standard Class
10191   10192  US-2026-156720  12/30/2026   1/3/2027  Standard Class
10192   10193  US-2026-143259  12/30/2026   1/3/2027  Standard Class
10193   10194  CA-2026-143500  12/30/2026   1/3/2027  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ... Postal Code   Region       Product ID  \
0            Houston  ...       77095  Central  OFF-PA-10000174
1         Naperville  ...       60540  Central  OFF-BI-10004094
2         Naperville  ...       60540  Central  OFF-LA-10003223
3         Naperville  ...       60540  Central  OFF-ST-10002743
4       Philadelphia  ...       19143     East  OFF-AR-10003478
...              ...  ...         ...      ...              ...
10189  New York City  ...       10009     East  OFF-BI-10003684
10190      Fairfield  ...       94533     West  OFF-BI-10004632
10191       Loveland  ...       80538     West  OFF-FA-10003472
10192  New York City  ...       10009     East  TEC-PH-10004774
10193  Charlottetown  ...         C0A     East  OFF-BI-10004040

              Category Sub-Category  \
0      Office Supplies        Paper
1      Office Supplies      Binders
2      Office Supplies       Labels
3      Office Supplies      Storage
4      Office Supplies          Art
...                ...          ...
10189  Office Supplies      Binders
10190  Office Supplies      Binders
10191  Office Supplies    Fasteners
10192       Technology       Phones
10193  Office Supplies      Binders

                                            Product Name    Sales  Quantity  \
0      Message Book, Wirebound, Four 5 1/2" X 4" Form...   16.448         2
1             GBC Standard Plastic Binding Systems Combs    3.540         2
2                                              Avery 508   11.784         3
3                          SAFCO Boltless Steel Shelving  272.736         3
4      Avery Hi-Liter EverBold Pen Style Fluorescent ...   19.536         3
...                                                  ...      ...       ...
10189               Wilson Jones Legal Size Ring Binders   52.776         3
10190                                 GBC Binding covers   20.720         2
10191                                Bagged Rubber Bands    3.024         3
10192                          Gear Head AU3700S Headset   90.930         7
10193                        Wilson Jones Impact Binders    3.024         3

       Discount   Profit
0           0.2   5.5512
1           0.8  -5.4870
2           0.2   4.2717
3           0.2 -64.7748
4           0.2   4.8840
...         ...      ...
10189       0.2  19.7910
10190       0.2   6.4750
10191       0.2  -0.6048
10192       0.0   2.7279
10193       0.2  -0.6048

[10194 rows x 21 columns]>

In [9]:
#Random five rows
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7640,7641,US-2026-133641,5/14/2026,5/21/2026,Standard Class,EJ-14155,Eva Jacobs,Consumer,United States,Gulfport,...,39503,South,OFF-EN-10004955,Office Supplies,Envelopes,Fashion Color Clasp Envelopes,48.690,9,0.0,23.8581
3551,3552,US-2024-141810,11/2/2024,11/7/2024,Standard Class,BB-10990,Barry Blumstein,Corporate,United States,San Antonio,...,78207,Central,OFF-BI-10001524,Office Supplies,Binders,GBC Premium Transparent Covers with Diagonal L...,29.372,7,0.8,-46.9952
5733,5734,US-2025-109806,9/17/2025,9/22/2025,Standard Class,JS-15685,Jim Sink,Corporate,United States,Los Angeles,...,90036,West,OFF-AR-10004930,Office Supplies,Art,Turquoise Lead Holder with Pocket Clip,20.100,3,0.0,6.6330
6975,6976,US-2026-104220,1/30/2026,2/5/2026,Standard Class,BV-11245,Benjamin Venier,Corporate,United States,Des Moines,...,50315,Central,TEC-PH-10004614,Technology,Phones,AT&T 841000 Phone,207.000,3,0.0,51.7500
8509,8510,US-2026-145037,9/2/2026,9/7/2026,Second Class,TB-21055,Ted Butterfield,Consumer,United States,Meriden,...,6450,East,OFF-PA-10002499,Office Supplies,Paper,Xerox 1890,146.820,3,0.0,73.4100

In [10]:
print("Dataset shape:",df.shape)
print("number of rows:",df.shape[0])
print("number of columns:",df.shape[1])
print("total elements:",df.size)

Dataset shape: (10194, 21)
number of rows: 10194
number of columns: 21
total elements: 214074

In [11]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [12]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [13]:
df.info

<bound method DataFrame.info of        Row ID        Order ID  Order Date  Ship Date       Ship Mode  \
0           1  US-2023-103800    1/3/2023   1/7/2023  Standard Class
1           2  US-2023-112326    1/4/2023   1/8/2023  Standard Class
2           3  US-2023-112326    1/4/2023   1/8/2023  Standard Class
3           4  US-2023-112326    1/4/2023   1/8/2023  Standard Class
4           5  US-2023-141817    1/5/2023  1/12/2023  Standard Class
...       ...             ...         ...        ...             ...
10189   10190  US-2026-143259  12/30/2026   1/3/2027  Standard Class
10190   10191  US-2026-115427  12/30/2026   1/3/2027  Standard Class
10191   10192  US-2026-156720  12/30/2026   1/3/2027  Standard Class
10192   10193  US-2026-143259  12/30/2026   1/3/2027  Standard Class
10193   10194  CA-2026-143500  12/30/2026   1/3/2027  Standard Class

      Customer ID      Customer Name      Segment Country/Region  \
0        DP-13000      Darren Powers     Consumer  United States
1        PO-19195      Phillina Ober  Home Office  United States
2        PO-19195      Phillina Ober  Home Office  United States
3        PO-19195      Phillina Ober  Home Office  United States
4        MB-18085         Mick Brown     Consumer  United States
...           ...                ...          ...            ...
10189    PO-18865  Patrick O'Donnell     Consumer  United States
10190    EB-13975         Erica Bern    Corporate  United States
10191    JM-15580      Jill Matthias     Consumer  United States
10192    PO-18865  Patrick O'Donnell     Consumer  United States
10193    HO-15230        Harry Olson     Consumer         Canada

                City  ... Postal Code   Region       Product ID  \
0            Houston  ...       77095  Central  OFF-PA-10000174
1         Naperville  ...       60540  Central  OFF-BI-10004094
2         Naperville  ...       60540  Central  OFF-LA-10003223
3         Naperville  ...       60540  Central  OFF-ST-10002743
4       Philadelphia  ...       19143     East  OFF-AR-10003478
...              ...  ...         ...      ...              ...
10189  New York City  ...       10009     East  OFF-BI-10003684
10190      Fairfield  ...       94533     West  OFF-BI-10004632
10191       Loveland  ...       80538     West  OFF-FA-10003472
10192  New York City  ...       10009     East  TEC-PH-10004774
10193  Charlottetown  ...         C0A     East  OFF-BI-10004040

              Category Sub-Category  \
0      Office Supplies        Paper
1      Office Supplies      Binders
2      Office Supplies       Labels
3      Office Supplies      Storage
4      Office Supplies          Art
...                ...          ...
10189  Office Supplies      Binders
10190  Office Supplies      Binders
10191  Office Supplies    Fasteners
10192       Technology       Phones
10193  Office Supplies      Binders

                                            Product Name    Sales  Quantity  \
0      Message Book, Wirebound, Four 5 1/2" X 4" Form...   16.448         2
1             GBC Standard Plastic Binding Systems Combs    3.540         2
2                                              Avery 508   11.784         3
3                          SAFCO Boltless Steel Shelving  272.736         3
4      Avery Hi-Liter EverBold Pen Style Fluorescent ...   19.536         3
...                                                  ...      ...       ...
10189               Wilson Jones Legal Size Ring Binders   52.776         3
10190                                 GBC Binding covers   20.720         2
10191                                Bagged Rubber Bands    3.024         3
10192                          Gear Head AU3700S Headset   90.930         7
10193                        Wilson Jones Impact Binders    3.024         3

       Discount   Profit
0           0.2   5.5512
1           0.8  -5.4870
2           0.2   4.2717
3           0.2 -64.7748
4           0.2   4.8840
...         ...      ...
10189       0.2  19.7910
10190       0.2   6.4750
10191       0.2  -0.6048
10192       0.0   2.7279
10193       0.2  -0.6048

[10194 rows x 21 columns]>

In [14]:
df.describe()

             Row ID         Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000  10194.000000
mean    5097.500000    228.225854      3.791838      0.155385     28.673417
std     2942.898656    619.906839      2.228317      0.206249    232.465115
min        1.000000      0.444000      1.000000      0.000000  -6599.978000
25%     2549.250000     17.220000      2.000000      0.000000      1.760800
50%     5097.500000     53.910000      3.000000      0.200000      8.690000
75%     7645.750000    209.500000      5.000000      0.200000     29.297925
max    10194.000000  22638.480000     14.000000      0.800000   8399.976000

In [15]:
# Numerical columns
numerical_columns = df.select_dtypes(include=np.number).columns

print("Numerical Columns:")
print(numerical_columns)

Numerical Columns:
Index(['Row ID', 'Sales', 'Quantity', 'Discount', 'Profit'], dtype='object')

In [16]:
# Categorical columns
categorical_columns = df.select_dtypes(include="object").columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name'],
      dtype='object')

In [17]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [18]:
# Number of rows before removing null values
print("Rows before removing null values:", df.shape[0])

# Remove rows containing null values
df = df.dropna()

# Number of rows after removing null values
print("Rows after removing null values:", df.shape[0])

Rows before removing null values: 10194
Rows after removing null values: 10194

In [20]:
df = df.drop_duplicates()
print("Dataset shape after removing duplicates:", df.shape)

Dataset shape after removing duplicates: (10194, 21)

In [22]:
text_columns = ["Category", "Sub-Category", "Segment"]

for column in text_columns:
    df[column] = (
        df[column]
       .astype(str)
       .str.strip()
       .str.title()
    )

In [23]:
for column in text_columns:
    print("\n", column)
    print(df[column].unique())

 Category
['Office Supplies' 'Furniture' 'Technology']

 Sub-Category
['Paper' 'Binders' 'Labels' 'Storage' 'Art' 'Chairs' 'Fasteners' 'Phones'
 'Furnishings' 'Accessories' 'Bookcases' 'Envelopes' 'Appliances' 'Tables'
 'Supplies' 'Machines' 'Copiers']

 Segment
['Consumer' 'Home Office' 'Corporate']

In [24]:
print("Final Shape:", df.shape)
print("\nTotal Missing Values:", df.isnull().sum().sum())
print("Total Duplicate Rows:", df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Final Shape: (10194, 21)

Total Missing Values: 0
Total Duplicate Rows: 0

Data Types:
Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [28]:
numerical_features = [
    "Sales",
    "Quantity",
    "Discount",
    "Profit"
]

df[numerical_features].describe()

              Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

In [30]:
summary = pd.DataFrame({
    "Mean":df[numerical_features].mean(),
    "Median":df[numerical_features].median(),
    "Minimum":df[numerical_features].min(),
    "Maximum":df[numerical_features].max(),
    "Standard Deviation":df[numerical_features].std()
})

summary

                Mean  Median   Minimum    Maximum  Standard Deviation
Sales     228.225854   53.91     0.444  22638.480          619.906839
Quantity    3.791838    3.00     1.000     14.000            2.228317
Discount    0.155385    0.20     0.000      0.800            0.206249
Profit     28.673417    8.69 -6599.978   8399.976          232.465115

In [31]:
category_sales = (
    df.groupby("Category")["Sales"].sum().sort_values(ascending=False))
category_sales

Category
Technology         839893.2790
Furniture          754747.7613
Office Supplies    731893.3140
Name: Sales, dtype: float64

In [32]:
category_sales = (
    df.groupby("Category")["Profit"].sum().sort_values(ascending=False))
category_sales

Category
Technology         146543.3756
Office Supplies    126023.4434
Furniture           19729.9956
Name: Profit, dtype: float64

In [33]:
category_sales = (
    df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False))
category_sales

Sub-Category
Chairs         335768.2490
Phones         331842.6400
Storage        224644.5540
Tables         208020.1820
Binders        207354.8810
Machines       189925.0310
Accessories    167380.3180
Copiers        150745.2900
Bookcases      115361.2043
Appliances     108213.1850
Furnishings     95598.1260
Paper           79540.5380
Supplies        46725.4980
Art             27659.0140
Envelopes       16528.3620
Labels          12695.0420
Fasteners        8532.2400
Name: Sales, dtype: float64

In [42]:
region_profit = (
    df.groupby("Region")["Profit"].sum().sort_values(ascending=False))
region_profit

Region
West       110798.8170
East        94883.2603
South       46749.4303
Central     39865.3070
Name: Profit, dtype: float64